"""
Models module containing SQLAlchemy domain models and Pydantic schemas.
"""

from app.models.domain import (
    Base,
    Chat,
    Chunk,
    ChunkContentType,
    Document,
    DocumentStatus,
    Message,
    MessageRole,
    MessageType,
)
from app.models.schemas import (
    # Agent schemas
    AgentContext,
    AgentResponse,
    RAGSearchParams,
    RAGSearchResponse,
    ToolCall,
    ToolDefinition,
    ToolParameter,
    ToolResult,
    WebSearchParams,
    WebSearchResponse,
    # Chat schemas
    BranchCreate,
    BranchSwitch,
    ChatCreate,
    ChatDetailResponse,
    ChatListResponse,
    ChatResponse,
    ChatStreamChunk,
    ChatUpdate,
    ConversationHistory,
    MessageCreate,
    MessageResponse,
    StreamEvent,
    ToolCallEvent,
    # Document schemas
    ChunkResponse,
    DocumentDetailResponse,
    DocumentListResponse,
    DocumentResponse,
    DocumentUploadResponse,
    ProcessingProgress,
    ProcessingStatus,
    SearchResponse,
    SearchResult,
)

__all__ = [
    # Domain models
    "Base",
    "Document",
    "DocumentStatus",
    "Chunk",
    "ChunkContentType",
    "Chat",
    "Message",
    "MessageRole",
    "MessageType",
    # Document schemas
    "DocumentUploadResponse",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentDetailResponse",
    "ChunkResponse",
    "ProcessingStatus",
    "ProcessingProgress",
    "SearchResult",
    "SearchResponse",
    # Chat schemas
    "MessageCreate",
    "MessageResponse",
    "ChatCreate",
    "ChatUpdate",
    "ChatResponse",
    "ChatDetailResponse",
    "ChatListResponse",
    "BranchCreate",
    "BranchSwitch",
    "StreamEvent",
    "ChatStreamChunk",
    "ToolCallEvent",
    "ConversationHistory",
    # Agent schemas
    "ToolDefinition",
    "ToolParameter",
    "ToolCall",
    "ToolResult",
    "RAGSearchParams",
    "RAGSearchResponse",
    "WebSearchParams",
    "WebSearchResponse",
    "AgentResponse",
    "AgentContext",
]
