"""
Pydantic schemas for API request/response validation.
"""

from app.models.schemas.agent import (
    AgentContext,
    AgentResponse,
    AgentThought,
    FileReaderParams,
    FileReaderResponse,
    RAGSearchParams,
    RAGSearchResponse,
    RAGSearchResult,
    ToolCall,
    ToolDefinition,
    ToolParameter,
    ToolResult,
    WebSearchParams,
    WebSearchResponse,
    WebSearchResult,
)
from app.models.schemas.chat import (
    BranchCreate,
    BranchInfo,
    BranchSwitch,
    ChatCreate,
    ChatDetailResponse,
    ChatListResponse,
    ChatResponse,
    ChatStreamChunk,
    ChatUpdate,
    ConversationHistory,
    MessageCreate,
    MessageResponse,
    StreamEvent,
    ToolCallEvent,
)
from app.models.schemas.document import (
    ChunkResponse,
    DocumentDetailResponse,
    DocumentListResponse,
    DocumentResponse,
    DocumentUploadResponse,
    ProcessingProgress,
    ProcessingStatus,
    SearchResponse,
    SearchResult,
)

__all__ = [
    # Document schemas
    "ChunkResponse",
    "DocumentDetailResponse",
    "DocumentListResponse",
    "DocumentResponse",
    "DocumentUploadResponse",
    "ProcessingProgress",
    "ProcessingStatus",
    "SearchResponse",
    "SearchResult",
    # Chat schemas
    "BranchCreate",
    "BranchInfo",
    "BranchSwitch",
    "ChatCreate",
    "ChatDetailResponse",
    "ChatListResponse",
    "ChatResponse",
    "ChatStreamChunk",
    "ChatUpdate",
    "ConversationHistory",
    "MessageCreate",
    "MessageResponse",
    "StreamEvent",
    "ToolCallEvent",
    # Agent schemas
    "AgentContext",
    "AgentResponse",
    "AgentThought",
    "FileReaderParams",
    "FileReaderResponse",
    "RAGSearchParams",
    "RAGSearchResponse",
    "RAGSearchResult",
    "ToolCall",
    "ToolDefinition",
    "ToolParameter",
    "ToolResult",
    "WebSearchParams",
    "WebSearchResponse",
    "WebSearchResult",
]
